"""Pipeline: export the in-house Edge model to the Sauron product site.

This repo (the Edge) is the in-house MODEL + viewer. **Sauron** is the consumer
product: a lightweight static site that just displays the model's output. This
script runs the model at the launch configuration and writes a single data file
the Sauron front-end loads (current 10-stock book + 2-year backtest curve +
headline stats). Re-run it whenever you want to push fresh picks to the product.

Product configuration (the spots that read "N/A" in the Sauron mockup):
  * 2-year window   * 1-month rebalance (hold=21)   * 75% YoY-rev-growth mix
  * 10-stock equal-weight book   (n=10 comes from EDGE_SPEC / edge_tracker_lib.N)

Output is written as JS (window.SAURON_DATA = {...}) rather than JSON so the
static site works when opened directly (file://) without a server or CORS/API
key. That IS the pipeline: model -> sauron_data.js -> static product.

Usage:  .venv/Scripts/python.exe export_sauron.py [--out PATH]
Default out: ../sauron/sauron_data.js
"""
from __future__ import annotations
import argparse
import json
import os
from datetime import datetime, timezone

import edge_lib
import edge_tracker_lib

WINDOW = "2Y"      # 2-year backtest window
HOLD = 21          # 1-month rebalance clock
MIX = 0.75         # 75% YoY-revenue-growth mix
# basket size n=10 is the product book (edge_lib.EDGE_SPEC / edge_tracker_lib.N)


def build() -> dict:
    bt = edge_lib.run_edge_backtest(window=WINDOW, spec={"hold": HOLD, "growth_mix": MIX})
    if not bt.get("ok"):
        raise SystemExit(f"backtest failed: {bt.get('reason')}")
    tr = edge_tracker_lib.tracker_state(hold=HOLD, window=WINDOW, mix=MIX)
    if not tr.get("ok"):
        raise SystemExit(f"tracker failed: {tr.get('reason')}")

    perf = bt["performance"]["model"]
    book = [{
        "ticker": b["ticker"], "name": b["name"], "sector": b["sector"],
        "weight": b["weight"], "accel": b.get("accel"),
    } for b in tr["current_book"]]

    return {
        "product": "Sauron",
        "config": {"window": WINDOW, "rebalance": "1M", "hold_days": HOLD,
                   "growth_mix": MIX, "n": len(book),
                   "cost_bps": bt["spec"].get("cost_bps", 10)},
        "as_of": tr["book_date"],
        "book_date": tr["book_date"],
        "book": book,
        "performance": {k: perf.get(k) for k in
                        ("cagr", "sharpe", "max_drawdown", "total_return")},
        "curve": {"dates": bt["curves"]["dates"],
                  "model": bt["curves"]["model"],
                  "sp500": bt["curves"]["sp500"]},
        "windows": bt["windows"],
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "disclaimer": "Backtest, net of ~10bps costs. Not a forecast or investment advice.",
    }


def main():
    ap = argparse.ArgumentParser()
    default_out = os.path.join(os.path.dirname(__file__), "..", "sauron", "sauron_data.js")
    ap.add_argument("--out", default=default_out)
    args = ap.parse_args()

    data = build()
    out = os.path.abspath(args.out)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    payload = "// Auto-generated by export_sauron.py — do not edit by hand.\n"
    payload += "window.SAURON_DATA = " + json.dumps(data, indent=2) + ";\n"
    with open(out, "w", encoding="utf-8") as f:
        f.write(payload)

    print(f"Wrote {out}")
    print(f"  as of {data['as_of']} · {data['config']['n']} names · "
          f"2Y CAGR {data['performance']['cagr']*100:.1f}% / "
          f"Sharpe {data['performance']['sharpe']:.2f}")
    print(f"  book: {', '.join(b['ticker'] for b in data['book'])}")


if __name__ == "__main__":
    main()
